package com.npower.dm.hibernate.entity;

import com.npower.dm.core.Favorite;
import com.npower.dm.core.FavoriteDevice;

/**
 * AbstractFavoriteDevice generated by MyEclipse Persistence Tools
 */

public abstract class AbstractFavoriteDevice implements java.io.Serializable, FavoriteDevice {

  // Fields

  private Long     id;

  private Favorite favorite;

  private Long     deviceId;

  // Constructors

  /** default constructor */
  public AbstractFavoriteDevice() {
  }

  /** minimal constructor */
  public AbstractFavoriteDevice(Long id, Favorite favorite) {
    this.id = id;
    this.favorite = favorite;
  }

  /** full constructor */
  public AbstractFavoriteDevice(Long id, Favorite favorite, Long deviceId) {
    this.id = id;
    this.favorite = favorite;
    this.deviceId = deviceId;
  }

  // Property accessors

  /*
   * (non-Javadoc)
   * 
   * @see com.hcp.dm.test.hibernate.entity.FavoriteDevice#getId()
   */
  public Long getId() {
    return this.id;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.hcp.dm.test.hibernate.entity.FavoriteDevice#setId(java.lang.Long)
   */
  public void setId(Long id) {
    this.id = id;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.hcp.dm.test.hibernate.entity.FavoriteDevice#getFavorite()
   */
  public Favorite getFavorite() {
    return this.favorite;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.hcp.dm.test.hibernate.entity.FavoriteDevice#setFavorite(com.hcp.dm.test.hibernate.entity.FavoriteEntity)
   */
  public void setFavorite(Favorite favorite) {
    this.favorite = favorite;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.hcp.dm.test.hibernate.entity.FavoriteDevice#getDeviceId()
   */
  public Long getDeviceId() {
    return this.deviceId;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.hcp.dm.test.hibernate.entity.FavoriteDevice#setDeviceId(java.lang.Long)
   */
  public void setDeviceId(Long deviceId) {
    this.deviceId = deviceId;
  }

}