/**
 * $Header: /home/master/nWave-DM-Common/src/com/npower/dm/hibernate/entity/AbstractSoftware.java,v 1.10 2008/09/02 07:15:33 chenlei Exp $
 * $Revision: 1.10 $
 * $Date: 2008/09/02 07:15:33 $
 *
 * ===============================================================================================
 * License, Version 1.1
 *
 * Copyright (c) 1994-2006 NPower Network Software Ltd.  All rights reserved.
 *
 * This SOURCE CODE FILE, which has been provided by NPower as part
 * of a NPower product for use ONLY by licensed users of the product,
 * includes CONFIDENTIAL and PROPRIETARY information of NPower.
 *
 * USE OF THIS SOFTWARE IS GOVERNED BY THE TERMS AND CONDITIONS
 * OF THE LICENSE STATEMENT AND LIMITED WARRANTY FURNISHED WITH
 * THE PRODUCT.
 *
 * IN PARTICULAR, YOU WILL INDEMNIFY AND HOLD NPower, ITS RELATED
 * COMPANIES AND ITS SUPPLIERS, HARMLESS FROM AND AGAINST ANY CLAIMS
 * OR LIABILITIES ARISING OUT OF THE USE, REPRODUCTION, OR DISTRIBUTION
 * OF YOUR PROGRAMS, INCLUDING ANY CLAIMS OR LIABILITIES ARISING OUT OF
 * OR RESULTING FROM THE USE, MODIFICATION, OR DISTRIBUTION OF PROGRAMS
 * OR FILES CREATED FROM, BASED ON, AND/OR DERIVED FROM THIS SOURCE
 * CODE FILE.
 * ===============================================================================================
 */
package com.npower.dm.hibernate.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import java.util.TreeSet;

import com.npower.dm.core.Software;
import com.npower.dm.core.SoftwarePackage;
import com.npower.dm.core.SoftwareScreenShot;
import com.npower.dm.core.SoftwareVendor;

/**
 * AbstractSoftware generated by MyEclipse Persistence Tools
 * 
 * @author Zhao DongLu
 * @version $Revision: 1.10 $ $Date: 2008/09/02 07:15:33 $
 */
public abstract class AbstractSoftware implements java.io.Serializable, Software {

  // Fields

  private long                   id;

  private SoftwareVendor   vendor;

  private String                 externalId;

  private String                 name;

  private String                 version;
  
  private String                 status = Software.STATUS_TEST;

  private String                 licenseType;

  private String                   description;
  
  private Date createdTime = new Date();
  private Date lastUpdatedTime = new Date();
  private String createdBy = null;
  private String lastUpdatedBy = null;
  private long changeVersion = 0;

  private Set<? extends SoftwarePackage>                    packages     = new HashSet<SoftwarePackageEntity>(0);

  private Set<? extends SoftwareScreenShot>                    screenShoots = new HashSet<SoftwareScreenShotEntity>(0);

  private Set<SoftwareCategoriesEntity>                    softwareCategoriesSet = new TreeSet<SoftwareCategoriesEntity>();
  private Set<SoftwareRecommendEntity>                    recommends = new TreeSet<SoftwareRecommendEntity>();

  private Set<? extends VSoftwareTrackLogAll>            ratings = new HashSet<VSoftwareTrackLogAll>(0);
  private Set<? extends VSoftwareTrackLogDaily>            ratingsDaily = new HashSet<VSoftwareTrackLogDaily>(0);
  private Set<? extends VSoftwareTrackLogWeekly>            ratingsWeekly = new HashSet<VSoftwareTrackLogWeekly>(0);
  private Set<? extends VSoftwareTrackLogMonthly>            ratingsMonthly = new HashSet<VSoftwareTrackLogMonthly>(0);
  private Set<? extends VSoftwareTrackLogYearly>            ratingsYearly = new HashSet<VSoftwareTrackLogYearly>(0);

  private Set<? extends SoftwareEvaluateEntity>                   softwareEvaluateEntity = new HashSet<SoftwareEvaluateEntity>(0);
  
  // Constructors

  /** default constructor */
  public AbstractSoftware() {
    super();
  }

  /** minimal constructor */
  public AbstractSoftware(long softwareId, String externalId, String name) {
    this.id = softwareId;
    this.externalId = externalId;
    this.name = name;
  }

  // Property accessors

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.IS#getId()
   */
  public long getId() {
    return this.id;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.IS#setId(long)
   */
  public void setId(long softwareId) {
    this.id = softwareId;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.IS#getVendor()
   */
  public SoftwareVendor getVendor() {
    return this.vendor;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.IS#setVendor(com.npower.dm.hibernate.entity.SoftwareVendorEntity)
   */
  public void setVendor(SoftwareVendor vendor) {
    this.vendor = vendor;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.IS#getExternalId()
   */
  public String getExternalId() {
    return this.externalId;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.IS#setExternalId(java.lang.String)
   */
  public void setExternalId(String externalId) {
    this.externalId = externalId;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.IS#getName()
   */
  public String getName() {
    return this.name;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.IS#setName(java.lang.String)
   */
  public void setName(String name) {
    this.name = name;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.IS#getVersion()
   */
  public String getVersion() {
    return this.version;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.IS#setVersion(java.lang.String)
   */
  public void setVersion(String version) {
    this.version = version;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.IS#getLicenseType()
   */
  public String getLicenseType() {
    return this.licenseType;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.IS#setLicenseType(java.lang.String)
   */
  public void setLicenseType(String licenseType) {
    this.licenseType = licenseType;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.IS#getDescription()
   */
  public String getDescription() {
    return this.description;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.IS#setDescription(java.sql.Clob)
   */
  public void setDescription(String description) {
    this.description = description;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.IS#getPackages()
   */
  public Set getPackages() {
    return this.packages;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.IS#setPackages(java.util.Set)
   */
  public void setPackages(Set packages) {
    this.packages = packages;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.IS#getScreenShoots()
   */
  public Set<? extends SoftwareScreenShot> getScreenShoots() {
    return this.screenShoots;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.IS#setScreenShoots(java.util.Set)
   */
  public void setScreenShoots(Set<? extends SoftwareScreenShot> screenShoots) {
    this.screenShoots = screenShoots;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.AAA#getRatings()
   */
  public Set<? extends VSoftwareTrackLogAll> getRatings() {
    return this.ratings;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.AAA#setRatings(java.util.Set)
   */
  public void setRatings(Set<? extends VSoftwareTrackLogAll> ratings) {
    this.ratings = ratings;
  }

  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public Date getCreatedTime() {
    return createdTime;
  }

  public void setCreatedTime(Date createdTime) {
    this.createdTime = createdTime;
  }

  public Date getLastUpdatedTime() {
    return lastUpdatedTime;
  }

  public void setLastUpdatedTime(Date lastUpdatedTime) {
    this.lastUpdatedTime = lastUpdatedTime;
  }

  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createBy) {
    this.createdBy = createBy;
  }

  public String getLastUpdatedBy() {
    return lastUpdatedBy;
  }

  public void setLastUpdatedBy(String lastUpdatedBy) {
    this.lastUpdatedBy = lastUpdatedBy;
  }

  public long getChangeVersion() {
    return changeVersion;
  }

  public void setChangeVersion(long changeVersion) {
    this.changeVersion = changeVersion;
  }

  public Set<SoftwareCategoriesEntity> getSoftwareCategoriesSet() {
    return softwareCategoriesSet;
  }

  public void setSoftwareCategoriesSet(Set<SoftwareCategoriesEntity> softwareCategoriesSet) {
    this.softwareCategoriesSet = softwareCategoriesSet;
  }

  public Set<SoftwareRecommendEntity> getRecommends() {
    return recommends;
  }

  public void setRecommends(Set<SoftwareRecommendEntity> recommends) {
    this.recommends = recommends;
  }

  /**
   * @return the ratingsDaily
   */
  public Set<? extends VSoftwareTrackLogDaily> getRatingsDaily() {
    return ratingsDaily;
  }

  /**
   * @param ratingsDaily the ratingsDaily to set
   */
  public void setRatingsDaily(Set<? extends VSoftwareTrackLogDaily> ratingsDaily) {
    this.ratingsDaily = ratingsDaily;
  }

  /**
   * @return the ratingsWeekly
   */
  public Set<? extends VSoftwareTrackLogWeekly> getRatingsWeekly() {
    return ratingsWeekly;
  }

  /**
   * @param ratingsWeekly the ratingsWeekly to set
   */
  public void setRatingsWeekly(Set<? extends VSoftwareTrackLogWeekly> ratingsWeekly) {
    this.ratingsWeekly = ratingsWeekly;
  }

  /**
   * @return the ratingsMonthly
   */
  public Set<? extends VSoftwareTrackLogMonthly> getRatingsMonthly() {
    return ratingsMonthly;
  }

  /**
   * @param ratingsMonthly the ratingsMonthly to set
   */
  public void setRatingsMonthly(Set<? extends VSoftwareTrackLogMonthly> ratingsMonthly) {
    this.ratingsMonthly = ratingsMonthly;
  }

  /**
   * @return the ratingsYearly
   */
  public Set<? extends VSoftwareTrackLogYearly> getRatingsYearly() {
    return ratingsYearly;
  }

  /**
   * @param ratingsYearly the ratingsYearly to set
   */
  public void setRatingsYearly(Set<? extends VSoftwareTrackLogYearly> ratingsYearly) {
    this.ratingsYearly = ratingsYearly;
  }

  public Set<? extends SoftwareEvaluateEntity> getSoftwareEvaluate() {
    return softwareEvaluateEntity;
  }

  public void setSoftwareEvaluate(Set<? extends SoftwareEvaluateEntity> softwareEvaluateEntity) {
    this.softwareEvaluateEntity = softwareEvaluateEntity;
  }

}