package com.npower.dm.hibernate.entity;

import com.npower.dm.core.ProfileConfig;



/**
 * AbstractAutoJobProfileConfig generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractAutoJobProfileConfig  implements java.io.Serializable {


    // Fields    

     private AutoJobProfileConfigId id;
     private ProfileConfig profileConfig;


    // Constructors

    /** default constructor */
    public AbstractAutoJobProfileConfig() {
    }

	/** minimal constructor */
    public AbstractAutoJobProfileConfig(AutoJobProfileConfigId id) {
        this.id = id;
    }
    
    /** full constructor */
    public AbstractAutoJobProfileConfig(AutoJobProfileConfigId id, ProfileConfig profileConfig) {
        this.id = id;
        this.profileConfig = profileConfig;
    }

   
    // Property accessors

    public AutoJobProfileConfigId getId() {
        return this.id;
    }
    
    public void setId(AutoJobProfileConfigId id) {
        this.id = id;
    }

    public ProfileConfig getProfileConfig() {
        return this.profileConfig;
    }
    
    public void setProfileConfig(ProfileConfig profileConfig) {
        this.profileConfig = profileConfig;
    }
   








}