package com.npower.dm.hibernate.entity;

import com.npower.dm.core.AutomaticProvisionJob;

/**
 * AbstractAutoJobNodesDiscoverId generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractAutoJobNodesDiscoverId implements java.io.Serializable {

  // Fields

  private AutomaticProvisionJob autoProvisionJob;

  private long             nodeIndex;

  // Constructors

  /** default constructor */
  public AbstractAutoJobNodesDiscoverId() {
  }

  /** full constructor */
  public AbstractAutoJobNodesDiscoverId(AutomaticProvisionJob autoProvisionJob, long nodeIndex) {
    this.autoProvisionJob = autoProvisionJob;
    this.nodeIndex = nodeIndex;
  }

  // Property accessors

  public long getNodeIndex() {
    return this.nodeIndex;
  }

  public void setNodeIndex(long nodeIndex) {
    this.nodeIndex = nodeIndex;
  }

  /**
   * @return the autoProvisionJob
   */
  public AutomaticProvisionJob getAutoProvisionJob() {
    return autoProvisionJob;
  }

  /**
   * @param autoProvisionJob
   *          the autoProvisionJob to set
   */
  public void setAutoProvisionJob(AutomaticProvisionJob autoProvisionJob) {
    this.autoProvisionJob = autoProvisionJob;
  }

  public boolean equals(Object other) {
    if ((this == other))
      return true;
    if ((other == null))
      return false;
    if (!(other instanceof AbstractAutoJobNodesDiscoverId))
      return false;
    AbstractAutoJobNodesDiscoverId castOther = (AbstractAutoJobNodesDiscoverId) other;

    return ((this.getAutoProvisionJob() == castOther.getAutoProvisionJob()) || (this.getAutoProvisionJob() != null
        && castOther.getAutoProvisionJob() != null && this.getAutoProvisionJob()
        .equals(castOther.getAutoProvisionJob())))
        && ((this.getNodeIndex() == castOther.getNodeIndex()) || (this.getNodeIndex() != 0
            && castOther.getNodeIndex() != 0 && this.getNodeIndex() == castOther.getNodeIndex()));
  }

  public int hashCode() {
    int result = 17;

    result = 37 * result + (getAutoProvisionJob() == null ? 0 : this.getAutoProvisionJob().hashCode());
    result = 37 * result + (getNodeIndex() == 0 ? 0 : (int)this.getNodeIndex());
    return result;
  }

}