package com.npower.dm.hibernate.entity;
// default package
// Generated by MyEclipse - Hibernate Tools

import java.util.Date;

/**
 * AuditLogEntity generated by MyEclipse - Hibernate Tools
 */
public class AuditLogEntity extends AbstractAuditLogEntity implements java.io.Serializable {

  // Constructors

  /** default constructor */
  public AuditLogEntity() {
  }

  /** minimal constructor */
  public AuditLogEntity(AuditLogAction action, String userName, Date creationDate) {
    super(action, userName, creationDate);
  }

  /** full constructor */
  public AuditLogEntity(AuditLogAction action, String userName, Date creationDate, String description) {
    super(action, userName, creationDate, description);
  }

}
