package com.npower.dm.hibernate.entity;
// default package
// Generated by MyEclipse - Hibernate Tools

/**
 * AuditLogTargetEntity generated by MyEclipse - Hibernate Tools
 */
public class AuditLogTargetEntity extends AbstractAuditLogTargetEntity implements java.io.Serializable {

  // Constructors

  /** default constructor */
  public AuditLogTargetEntity() {
  }

}
