package com.npower.dm.hibernate.entity;

import java.util.Date;

/**
 * DmTrackingLogDetail generated by MyEclipse Persistence Tools
 */

public class DmTrackingLogDetail extends AbstractDmTrackingLogDetail implements java.io.Serializable {

  // Fields

  /** default constructor */
  public DmTrackingLogDetail() {
  }

  /** minimal constructor */
  public DmTrackingLogDetail(String deviceId, String sessionId, long requestSum, long responseSum,String clientIp ,String userAgent) {
    super(deviceId, sessionId, requestSum, responseSum, clientIp, userAgent);
  }

  /** full constructor */
  public DmTrackingLogDetail(long jobId, String deviceId, String sessionId, Date beginTimeStamp, Date endTimeStamp,
      long requestSum, long responseSum,String clientIp ,String userAgent) {
    super(jobId, deviceId, sessionId, beginTimeStamp, endTimeStamp, requestSum, responseSum, clientIp, userAgent);
  }

  /**
   * Return duration time in milliseconds.
   * @return
   */
  public long getDuration(){
    if (this.getBeginTimeStamp() == null || this.getEndTimeStamp() == null) {
      return 0;
    } else {
      long result = this.getEndTimeStamp().getTime() - this.getBeginTimeStamp().getTime();
      return result;
    }
  }
}