package com.npower.dm.hibernate.entity;

// Generated by MyEclipse Persistence Tools

import java.util.Set;

import com.npower.dm.core.FavoriteDevice;


/**
 * Favorite generated by MyEclipse Persistence Tools
 */
public class FavoriteEntity extends AbstractFavorite implements java.io.Serializable {

  // Constructors

  /**
   * 
   */
  private static final long serialVersionUID = 1L;

  /** default constructor */
  public FavoriteEntity() {
  }

  /** minimal constructor */
  public FavoriteEntity(Long favoriteId, String name, boolean shared) {
    super(favoriteId, name, shared);
  }

  /** full constructor */
  public FavoriteEntity(Long favoriteId, String name, String description, boolean shared, String owner, Set<FavoriteDevice> FavoriteDevices) {
    super(favoriteId, name, description, shared, owner, FavoriteDevices);
  }

}
