/**
 * $Header: /home/master/nWave-DM-Common/src/com/npower/dm/hibernate/entity/SoftwareEntity.java,v 1.10 2008/09/03 08:44:24 zhao Exp $
 * $Revision: 1.10 $
 * $Date: 2008/09/03 08:44:24 $
 *
 * ===============================================================================================
 * License, Version 1.1
 *
 * Copyright (c) 1994-2006 NPower Network Software Ltd.  All rights reserved.
 *
 * This SOURCE CODE FILE, which has been provided by NPower as part
 * of a NPower product for use ONLY by licensed users of the product,
 * includes CONFIDENTIAL and PROPRIETARY information of NPower.
 *
 * USE OF THIS SOFTWARE IS GOVERNED BY THE TERMS AND CONDITIONS
 * OF THE LICENSE STATEMENT AND LIMITED WARRANTY FURNISHED WITH
 * THE PRODUCT.
 *
 * IN PARTICULAR, YOU WILL INDEMNIFY AND HOLD NPower, ITS RELATED
 * COMPANIES AND ITS SUPPLIERS, HARMLESS FROM AND AGAINST ANY CLAIMS
 * OR LIABILITIES ARISING OUT OF THE USE, REPRODUCTION, OR DISTRIBUTION
 * OF YOUR PROGRAMS, INCLUDING ANY CLAIMS OR LIABILITIES ARISING OUT OF
 * OR RESULTING FROM THE USE, MODIFICATION, OR DISTRIBUTION OF PROGRAMS
 * OR FILES CREATED FROM, BASED ON, AND/OR DERIVED FROM THIS SOURCE
 * CODE FILE.
 * ===============================================================================================
 */
package com.npower.dm.hibernate.entity;

import java.util.Iterator;
import java.util.Set;
import java.util.TreeSet;

import org.apache.commons.lang.StringUtils;

import com.npower.dm.core.Software;
import com.npower.dm.core.SoftwareCategory;
import com.npower.dm.core.SoftwareTopNRate;
import com.npower.dm.management.SoftwareTrackingType;

/**
 * SoftwareEntity generated by MyEclipse Persistence Tools
 * 
 * @author Zhao DongLu
 * @version $Revision: 1.10 $ $Date: 2008/09/03 08:44:24 $
 */
public class SoftwareEntity extends AbstractSoftware implements java.io.Serializable, Software, Comparable<Software> {

  // Constructors

  /**
   * 
   */
  private static final long serialVersionUID = 4233273728872965094L;

  /** default constructor */
  public SoftwareEntity() {
  }

  /** minimal constructor */
  public SoftwareEntity(long softwareId, String externalId, String name) {
    super(softwareId, externalId, name);
  }

  /* (non-Javadoc)
   * @see java.lang.Comparable#compareTo(java.lang.Object)
   */
  public int compareTo(Software o) {
    if (o == null) {
       return 1;
    }
    if (StringUtils.isEmpty(this.getName()) && StringUtils.isEmpty(this.getName())) {
       return 0;
    } else if (StringUtils.isEmpty(this.getName())) {
      return -1;
    } else {
      return this.getName().compareTo(o.getName());
    }
  }

  /* (non-Javadoc)
   * @see com.npower.dm.core.Software#getCategory()
   */
  public SoftwareCategory getCategory() {
    // Return first.
    Iterator<SoftwareCategoriesEntity> iterator = this.getSoftwareCategoriesSet().iterator();
    if (iterator.hasNext()) {
       return iterator.next().getId().getCategory();
    } else {
      throw new RuntimeException("Software[" + this.getId() + "], name=" + this.getName() + " missing SoftwareCategory.");
      //return null;
    }
  }

  /* (non-Javadoc)
   * @see com.npower.dm.core.Software#getCategoryies()
   */
  public Set<SoftwareCategory> getCategoryies() {
    Set<SoftwareCategory> categories = new TreeSet<SoftwareCategory>();
    for (SoftwareCategoriesEntity e: this.getSoftwareCategoriesSet()) {
        categories.add(e.getId().getCategory());
    }
    return categories;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.core.Software#getRating(com.npower.dm.management.SoftwareTrackingType)
   */
  public long getRating(SoftwareTrackingType type) {
    int result = 0;
    for (SoftwareTopNRate rating: this.getRatings()) {
        if (type.toString().equals(rating.getTrackingType())) {
           result += rating.getCount();
        }
    }
    return result;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.core.Software#getRatingView()
   */
  public long getRatingView() {
    return getRating(SoftwareTrackingType.VIEW);
  }

  /* (non-Javadoc)
   * @see com.npower.dm.core.Software#getRatingDownload()
   */
  public long getRatingDownload() {
    return getRating(SoftwareTrackingType.DOWNLOAD);
  }

  /* (non-Javadoc)
   * @see com.npower.dm.core.Software#getRatingInstall()
   */
  public long getRatingInstall() {
    return getRating(SoftwareTrackingType.INSTALLED);
  }

}
