package com.npower.dm.hibernate.entity;

import com.npower.dm.core.Software;
import com.npower.dm.core.SoftwarePackage;

/**
 * VSoftwareTrackLogYearly generated by MyEclipse Persistence Tools
 */

public class VSoftwareTrackLogYearly extends AbstractVSoftwareTrackLogYearly implements java.io.Serializable {

  // Fields

  /** default constructor */
  public VSoftwareTrackLogYearly() {
  }

  /** minimal constructor */
  public VSoftwareTrackLogYearly(long id, String trackingType) {
    super(id, trackingType);
  }

  /** full constructor */
  public VSoftwareTrackLogYearly(long id, Software software, SoftwarePackage softwarePackage, String trackingType, String year, long count) {
    super(id, software, softwarePackage, trackingType, year,count);
  }

}