/**
  * $Header: /home/master/nWave-DM-Common/src/com/npower/dm/server/synclet/BootstrapPhoneNumberDetector.java,v 1.4 2008/03/11 03:43:32 zhao Exp $
  * $Revision: 1.4 $
  * $Date: 2008/03/11 03:43:32 $
  *
  * ===============================================================================================
  * License, Version 1.1
  *
  * Copyright (c) 1994-2006 NPower Network Software Ltd.  All rights reserved.
  *
  * This SOURCE CODE FILE, which has been provided by NPower as part
  * of a NPower product for use ONLY by licensed users of the product,
  * includes CONFIDENTIAL and PROPRIETARY information of NPower.
  *
  * USE OF THIS SOFTWARE IS GOVERNED BY THE TERMS AND CONDITIONS
  * OF THE LICENSE STATEMENT AND LIMITED WARRANTY FURNISHED WITH
  * THE PRODUCT.
  *
  * IN PARTICULAR, YOU WILL INDEMNIFY AND HOLD NPower, ITS RELATED
  * COMPANIES AND ITS SUPPLIERS, HARMLESS FROM AND AGAINST ANY CLAIMS
  * OR LIABILITIES ARISING OUT OF THE USE, REPRODUCTION, OR DISTRIBUTION
  * OF YOUR PROGRAMS, INCLUDING ANY CLAIMS OR LIABILITIES ARISING OUT OF
  * OR RESULTING FROM THE USE, MODIFICATION, OR DISTRIBUTION OF PROGRAMS
  * OR FILES CREATED FROM, BASED ON, AND/OR DERIVED FROM THIS SOURCE
  * CODE FILE.
  * ===============================================================================================
  */
package com.npower.dm.server.synclet;

import javax.servlet.http.HttpServletRequest;

import sync4j.framework.core.SyncML;

import com.npower.dm.bootstrap.BootstrapService;
import com.npower.dm.bootstrap.URLParameters;

/**
 * Detect phone number from Server URL generated by bootstrap
 * @author Zhao DongLu
 * @version $Revision: 1.4 $ $Date: 2008/03/11 03:43:32 $
 */
public class BootstrapPhoneNumberDetector implements PhoneNumberDetector {

  /**
   * Default constructor.
   */
  public BootstrapPhoneNumberDetector() {
    super();
  }

  /* (non-Javadoc)
   * @see com.npower.dm.server.synclet.PhoneNumberParser#getPhoneNumber(java.lang.String, javax.servlet.http.HttpServletRequest, sync4j.framework.core.SyncML)
   */
  public String getPhoneNumber(String deviceExternalID, HttpServletRequest httpRequest, SyncML message) {
    String bsp = httpRequest.getParameter(BootstrapService.BOOTSTRAP_PARAMETRERS_NAME);
    URLParameters params = URLParameters.decode(bsp);
    if (params == null) {
      return null;
    }
    String msisdn = params.getMsisdn();
    return msisdn;
  }

}
