package com.npower.unicom;



/**
 * VCPCDRLog generated by MyEclipse Persistence Tools
 */

public class VCPCDRLog implements java.io.Serializable {

  // Fields

  private Long   logId;

  private String phonenumber;

  private String web;

  private String manufacturer;

  private String model;

  private String imei;

  private String workType;

  private String status;

  private String province;

  private String costType;

  private String functionCost;

  private String  startTime;

  private String  endTime;

  // Constructors

  /** default constructor */
  public VCPCDRLog() {
  }

  /** minimal constructor */
  public VCPCDRLog(String phonenumber, String status, String startTime, String endTime) {
    this.phonenumber = phonenumber;
    this.status = status;
    this.startTime = startTime;
    this.endTime = endTime;
  }

  /** full constructor */
  public VCPCDRLog(String phonenumber, String web, String manufacturer, String model, String imei,
      String workType, String status, String province, String costType, String functionCost, String startTime,
      String endTime) {
    this.phonenumber = phonenumber;
    this.web = web;
    this.manufacturer = manufacturer;
    this.model = model;
    this.imei = imei;
    this.workType = workType;
    this.status = status;
    this.province = province;
    this.costType = costType;
    this.functionCost = functionCost;
    this.startTime = startTime;
    this.endTime = endTime;
  }

  // Property accessors

  public Long getLogId() {
    return this.logId;
  }

  public void setLogId(Long logId) {
    this.logId = logId;
  }

  public String getPhonenumber() {
    return this.phonenumber;
  }

  public void setPhonenumber(String phonenumber) {
    this.phonenumber = phonenumber;
  }

  public String getWeb() {
    return this.web;
  }

  public void setWeb(String web) {
    this.web = web;
  }

  public String getManufacturer() {
    return this.manufacturer;
  }

  public void setManufacturer(String manufacturer) {
    this.manufacturer = manufacturer;
  }

  public String getModel() {
    return this.model;
  }

  public void setModel(String model) {
    this.model = model;
  }

  public String getImei() {
    return this.imei;
  }

  public void setImei(String imei) {
    this.imei = imei;
  }

  public String getWorkType() {
    return this.workType;
  }

  public void setWorkType(String workType) {
    this.workType = workType;
  }

  public String getStatus() {
    return this.status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public String getProvince() {
    return this.province;
  }

  public void setProvince(String province) {
    this.province = province;
  }

  public String getCostType() {
    return this.costType;
  }

  public void setCostType(String costType) {
    this.costType = costType;
  }

  public String getFunctionCost() {
    return this.functionCost;
  }

  public void setFunctionCost(String functionCost) {
    this.functionCost = functionCost;
  }

  public String getStartTime() {
    return this.startTime;
  }

  public void setStartTime(String startTime) {
    this.startTime = startTime;
  }

  public String getEndTime() {
    return this.endTime;
  }

  public void setEndTime(String endTime) {
    this.endTime = endTime;
  }

}