# Auto-generated by EclipseNSIS Script Wizard
# 2011-8-30 22:51:56

Name "ICBC HTTP DNS Probe V2"

# General Symbol Definitions
!define REGKEY "SOFTWARE\$(^Name)"
!define VERSION 2.0
!define COMPANY ICBC
!define URL ""

# Included files
!include Sections.nsh

# Variables
Var StartMenuGroup

# Installer pages
Page instfiles

# Installer attributes
OutFile setup.exe
InstallDir c:\icbc-probe
CRCCheck on
XPStyle on
Icon "${NSISDIR}\Contrib\Graphics\Icons\classic-install.ico"
ShowInstDetails show
AutoCloseWindow false
VIProductVersion 2.0.0.0
VIAddVersionKey ProductName "ICBC HTTP DNS Probe V2"
VIAddVersionKey ProductVersion "${VERSION}"
VIAddVersionKey CompanyName "${COMPANY}"
VIAddVersionKey FileVersion "${VERSION}"
VIAddVersionKey FileDescription ""
VIAddVersionKey LegalCopyright ""
InstallDirRegKey HKLM "${REGKEY}" Path
UninstallIcon "${NSISDIR}\Contrib\Graphics\Icons\classic-uninstall.ico"
ShowUninstDetails show

# Installer sections
Section -Main SEC0000
    SetOutPath $INSTDIR
    SetOverwrite on
    File /r C:\Users\IBM_ADMIN\workspace\ICBC-Probe-Project\icbc-probe-assembly\target\icbc-probe\*
    WriteRegStr HKLM "${REGKEY}\Components" Main 1
SectionEnd

Section -post SEC0001
    WriteRegStr HKLM "${REGKEY}" Path $INSTDIR
    SetOutPath $INSTDIR
    WriteUninstaller $INSTDIR\uninstall.exe
    SetOutPath $SMPROGRAMS\$StartMenuGroup
    CreateShortcut "$SMPROGRAMS\$StartMenuGroup\Uninstall $(^Name).lnk" $INSTDIR\uninstall.exe
    WriteRegStr HKLM "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\$(^Name)" DisplayName "$(^Name)"
    WriteRegStr HKLM "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\$(^Name)" DisplayVersion "${VERSION}"
    WriteRegStr HKLM "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\$(^Name)" Publisher "${COMPANY}"
    WriteRegStr HKLM "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\$(^Name)" DisplayIcon $INSTDIR\uninstall.exe
    WriteRegStr HKLM "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\$(^Name)" UninstallString $INSTDIR\uninstall.exe
    WriteRegDWORD HKLM "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\$(^Name)" NoModify 1
    WriteRegDWORD HKLM "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\$(^Name)" NoRepair 1
    
    ; Processing [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tomcat6]
    WriteRegDWORD HKEY_LOCAL_MACHINE SYSTEM\CurrentControlSet\Services\Tomcat6 Type 16
    WriteRegDWORD HKEY_LOCAL_MACHINE SYSTEM\CurrentControlSet\Services\Tomcat6 Start 2
    WriteRegDWORD HKEY_LOCAL_MACHINE SYSTEM\CurrentControlSet\Services\Tomcat6 ErrorControl 1
    WriteRegStr HKEY_LOCAL_MACHINE SYSTEM\CurrentControlSet\Services\Tomcat6 ImagePath "C:\icbc-probe\bin\icbcprobe.exe //RS//Tomcat6"
    WriteRegStr HKEY_LOCAL_MACHINE SYSTEM\CurrentControlSet\Services\Tomcat6 DisplayName "ICBC Probe Client"
    WriteRegStr HKEY_LOCAL_MACHINE SYSTEM\CurrentControlSet\Services\Tomcat6 ObjectName LocalSystem
    WriteRegStr HKEY_LOCAL_MACHINE SYSTEM\CurrentControlSet\Services\Tomcat6 Description "ICBC Probe Client"
    
    ; Processing [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tomcat6\Parameters]
    Push $0
    Push $1
    ;HKEY_LOCAL_MACHINE = 0xffffffff80000002, REG_CREATE_SUBKEY = 0x0004
    System::Call /NOUNLOAD "Advapi32::RegCreateKeyExA(i, t, i, t, i, i, i, *i, i) i(0xffffffff80000002, 'SYSTEM\CurrentControlSet\Services\Tomcat6\Parameters', 0, '', 0, 0x0004, 0, .r0, 0) .r1"
    StrCmp $1 0 +2
    SetErrors
    StrCmp $0 0 +2
    System::Call /NOUNLOAD "Advapi32::RegCloseKey(i) i(r0) .r1"
    System::Free 0
    Pop $1
    Pop $0
    
    ; Processing [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tomcat6\Security]
    WriteRegBin HKEY_LOCAL_MACHINE SYSTEM\CurrentControlSet\Services\Tomcat6\Security Security 01001480900000009c000000140000003000000002001c000100000002801400ff010f00010100000000000100000000020060000400000000001400fd01020001010000000000051200000000001800ff010f0001020000000000052000000020020000000014008d01020001010000000000050b00000000001800fd01020001020000000000052000000023020000010100000000000512000000010100000000000512000000
    
    ; Processing [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tomcat6\Enum]
    WriteRegStr HKEY_LOCAL_MACHINE SYSTEM\CurrentControlSet\Services\Tomcat6\Enum 0 Root\LEGACY_TOMCAT6\0000
    WriteRegDWORD HKEY_LOCAL_MACHINE SYSTEM\CurrentControlSet\Services\Tomcat6\Enum Count 1
    WriteRegDWORD HKEY_LOCAL_MACHINE SYSTEM\CurrentControlSet\Services\Tomcat6\Enum NextInstance 1
    
    ; Processing [HKEY_LOCAL_MACHINE\SOFTWARE\Apache Software Foundation]
    Push $0
    Push $1
    ;HKEY_LOCAL_MACHINE = 0xffffffff80000002, REG_CREATE_SUBKEY = 0x0004
    System::Call /NOUNLOAD "Advapi32::RegCreateKeyExA(i, t, i, t, i, i, i, *i, i) i(0xffffffff80000002, 'SOFTWARE\Apache Software Foundation', 0, '', 0, 0x0004, 0, .r0, 0) .r1"
    StrCmp $1 0 +2
    SetErrors
    StrCmp $0 0 +2
    System::Call /NOUNLOAD "Advapi32::RegCloseKey(i) i(r0) .r1"
    System::Free 0
    Pop $1
    Pop $0
    
    ; Processing [HKEY_LOCAL_MACHINE\SOFTWARE\Apache Software Foundation\Procrun 2.0]
    Push $0
    Push $1
    ;HKEY_LOCAL_MACHINE = 0xffffffff80000002, REG_CREATE_SUBKEY = 0x0004
    System::Call /NOUNLOAD "Advapi32::RegCreateKeyExA(i, t, i, t, i, i, i, *i, i) i(0xffffffff80000002, 'SOFTWARE\Apache Software Foundation\Procrun 2.0', 0, '', 0, 0x0004, 0, .r0, 0) .r1"
    StrCmp $1 0 +2
    SetErrors
    StrCmp $0 0 +2
    System::Call /NOUNLOAD "Advapi32::RegCloseKey(i) i(r0) .r1"
    System::Free 0
    Pop $1
    Pop $0
    
    ; Processing [HKEY_LOCAL_MACHINE\SOFTWARE\Apache Software Foundation\Procrun 2.0\Tomcat6]
    Push $0
    Push $1
    ;HKEY_LOCAL_MACHINE = 0xffffffff80000002, REG_CREATE_SUBKEY = 0x0004
    System::Call /NOUNLOAD "Advapi32::RegCreateKeyExA(i, t, i, t, i, i, i, *i, i) i(0xffffffff80000002, 'SOFTWARE\Apache Software Foundation\Procrun 2.0\Tomcat6', 0, '', 0, 0x0004, 0, .r0, 0) .r1"
    StrCmp $1 0 +2
    SetErrors
    StrCmp $0 0 +2
    System::Call /NOUNLOAD "Advapi32::RegCloseKey(i) i(r0) .r1"
    System::Free 0
    Pop $1
    Pop $0
    
    ; Processing [HKEY_LOCAL_MACHINE\SOFTWARE\Apache Software Foundation\Procrun 2.0\Tomcat6\Parameters]
    Push $0
    Push $1
    ;HKEY_LOCAL_MACHINE = 0xffffffff80000002, REG_CREATE_SUBKEY = 0x0004
    System::Call /NOUNLOAD "Advapi32::RegCreateKeyExA(i, t, i, t, i, i, i, *i, i) i(0xffffffff80000002, 'SOFTWARE\Apache Software Foundation\Procrun 2.0\Tomcat6\Parameters', 0, '', 0, 0x0004, 0, .r0, 0) .r1"
    StrCmp $1 0 +2
    SetErrors
    StrCmp $0 0 +2
    System::Call /NOUNLOAD "Advapi32::RegCloseKey(i) i(r0) .r1"
    System::Free 0
    Pop $1
    Pop $0
    
    ; Processing [HKEY_LOCAL_MACHINE\SOFTWARE\Apache Software Foundation\Procrun 2.0\Tomcat6\Parameters\Java]
    WriteRegStr HKEY_LOCAL_MACHINE "SOFTWARE\Apache Software Foundation\Procrun 2.0\Tomcat6\Parameters\Java" Jvm C:\icbc-probe\java\jre\bin\client\jvm.dll
    WriteRegStr HKEY_LOCAL_MACHINE "SOFTWARE\Apache Software Foundation\Procrun 2.0\Tomcat6\Parameters\Java" Classpath C:\icbc-probe\bin\bootstrap.jar
    WriteRegStr HKEY_LOCAL_MACHINE "SOFTWARE\Apache Software Foundation\Procrun 2.0\Tomcat6\Parameters\Java" Options "-Dcatalina.home=C:\icbc-probe -Dcatalina.base=C:\icbc-probe -Djava.endorsed.dirs=C:\icbc-probe\endorsed -Djava.io.tmpdir=C:\icbc-probe\temp -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager -Djava.util.logging.config.file=C:\icbc-probe\conf\logging.properties"
    WriteRegDWORD HKEY_LOCAL_MACHINE "SOFTWARE\Apache Software Foundation\Procrun 2.0\Tomcat6\Parameters\Java" JvmMs 0
    WriteRegDWORD HKEY_LOCAL_MACHINE "SOFTWARE\Apache Software Foundation\Procrun 2.0\Tomcat6\Parameters\Java" JvmMx 0
    WriteRegDWORD HKEY_LOCAL_MACHINE "SOFTWARE\Apache Software Foundation\Procrun 2.0\Tomcat6\Parameters\Java" JvmSs 0
    
    ; Processing [HKEY_LOCAL_MACHINE\SOFTWARE\Apache Software Foundation\Procrun 2.0\Tomcat6\Parameters\Log]
    WriteRegStr HKEY_LOCAL_MACHINE "SOFTWARE\Apache Software Foundation\Procrun 2.0\Tomcat6\Parameters\Log" Path C:\icbc-probe\logs
    WriteRegStr HKEY_LOCAL_MACHINE "SOFTWARE\Apache Software Foundation\Procrun 2.0\Tomcat6\Parameters\Log" StdError auto
    WriteRegStr HKEY_LOCAL_MACHINE "SOFTWARE\Apache Software Foundation\Procrun 2.0\Tomcat6\Parameters\Log" StdOutput auto
    WriteRegStr HKEY_LOCAL_MACHINE "SOFTWARE\Apache Software Foundation\Procrun 2.0\Tomcat6\Parameters\Log" Level Info
    WriteRegStr HKEY_LOCAL_MACHINE "SOFTWARE\Apache Software Foundation\Procrun 2.0\Tomcat6\Parameters\Log" Prefix probe_service_
    
    ; Processing [HKEY_LOCAL_MACHINE\SOFTWARE\Apache Software Foundation\Procrun 2.0\Tomcat6\Parameters\Start]
    WriteRegStr HKEY_LOCAL_MACHINE "SOFTWARE\Apache Software Foundation\Procrun 2.0\Tomcat6\Parameters\Start" WorkingPath C:\icbc-probe
    WriteRegStr HKEY_LOCAL_MACHINE "SOFTWARE\Apache Software Foundation\Procrun 2.0\Tomcat6\Parameters\Start" Class org.apache.catalina.startup.Bootstrap
    WriteRegStr HKEY_LOCAL_MACHINE "SOFTWARE\Apache Software Foundation\Procrun 2.0\Tomcat6\Parameters\Start" Params start
    WriteRegStr HKEY_LOCAL_MACHINE "SOFTWARE\Apache Software Foundation\Procrun 2.0\Tomcat6\Parameters\Start" Mode jvm
    
    ; Processing [HKEY_LOCAL_MACHINE\SOFTWARE\Apache Software Foundation\Procrun 2.0\Tomcat6\Parameters\Stop]
    WriteRegStr HKEY_LOCAL_MACHINE "SOFTWARE\Apache Software Foundation\Procrun 2.0\Tomcat6\Parameters\Stop" WorkingPath C:\icbc-probe
    WriteRegStr HKEY_LOCAL_MACHINE "SOFTWARE\Apache Software Foundation\Procrun 2.0\Tomcat6\Parameters\Stop" Class org.apache.catalina.startup.Bootstrap
    WriteRegStr HKEY_LOCAL_MACHINE "SOFTWARE\Apache Software Foundation\Procrun 2.0\Tomcat6\Parameters\Stop" Params stop
    WriteRegStr HKEY_LOCAL_MACHINE "SOFTWARE\Apache Software Foundation\Procrun 2.0\Tomcat6\Parameters\Stop" Mode jvm
    WriteRegDWORD HKEY_LOCAL_MACHINE "SOFTWARE\Apache Software Foundation\Procrun 2.0\Tomcat6\Parameters\Stop" Timeout 0
    
SectionEnd

# Macro for selecting uninstaller sections
!macro SELECT_UNSECTION SECTION_NAME UNSECTION_ID
    Push $R0
    ReadRegStr $R0 HKLM "${REGKEY}\Components" "${SECTION_NAME}"
    StrCmp $R0 1 0 next${UNSECTION_ID}
    !insertmacro SelectSection "${UNSECTION_ID}"
    GoTo done${UNSECTION_ID}
next${UNSECTION_ID}:
    !insertmacro UnselectSection "${UNSECTION_ID}"
done${UNSECTION_ID}:
    Pop $R0
!macroend

# Uninstaller sections
Section /o -un.Main UNSEC0000
    RmDir /r /REBOOTOK $INSTDIR
    DeleteRegValue HKLM "${REGKEY}\Components" Main
SectionEnd

Section -un.post UNSEC0001
    DeleteRegKey HKLM "SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\$(^Name)"
    Delete /REBOOTOK "$SMPROGRAMS\$StartMenuGroup\Uninstall $(^Name).lnk"
    Delete /REBOOTOK $INSTDIR\uninstall.exe
    DeleteRegValue HKLM "${REGKEY}" Path
    DeleteRegKey /IfEmpty HKLM "${REGKEY}\Components"
    DeleteRegKey /IfEmpty HKLM "${REGKEY}"
    RmDir /REBOOTOK $SMPROGRAMS\$StartMenuGroup
    RmDir /REBOOTOK $INSTDIR
SectionEnd

# Installer functions
Function .onInstSuccess
    Exec $\"C:\icbc-probe\bin\post_inst.bat$\"
    
    # Alert and reboot
    MessageBox MB_YESNO|MB_ICONQUESTION|MB_TOPMOST "请立即重新启动系统, 确保安装程序能够正确完成!" IDNO +2
    Reboot
FunctionEnd

Function .onInit
    InitPluginsDir
    StrCpy $StartMenuGroup "ICBC HTTP DNS Probe V2"
    Exec $\"C:\icbc-probe\bin\uninst_v1.bat$\"
FunctionEnd

# Uninstaller functions
Function un.onInit
    ReadRegStr $INSTDIR HKLM "${REGKEY}" Path
    StrCpy $StartMenuGroup "ICBC HTTP DNS Probe V2"
    !insertmacro SELECT_UNSECTION Main ${UNSEC0000}
FunctionEnd
