package com.npower.dm.hibernate.entity;
// default package

/**
 * AbstractAuditLogAction generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractAuditLogAction implements java.io.Serializable {

  // Fields

  private String  value;

  private String  description;

  private String  type;

  private boolean optional = true;

  // Constructors

  /** default constructor */
  public AbstractAuditLogAction() {
  }

  /** minimal constructor */
  public AbstractAuditLogAction(String value, String description, String type, boolean optional) {
    this.value = value;
    this.description = description;
    this.type = type;
    this.optional = optional;
  }

  // Property accessors

  public String getValue() {
    return this.value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  public String getDescription() {
    return this.description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public String getType() {
    return this.type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public boolean getOptional() {
    return this.optional;
  }

  public void setOptional(boolean optional) {
    this.optional = optional;
  }

}