package com.npower.dm.hibernate.entity;

import java.util.HashSet;
import java.util.Set;

import com.npower.dm.core.Favorite;
import com.npower.dm.core.FavoriteDevice;

/**
 * AbstractDmFavorite generated by MyEclipse Persistence Tools
 */

public abstract class AbstractFavorite implements java.io.Serializable, Favorite {

  // Fields

  private Long        favoriteId;

  private String      name;

  private String      description;

  private boolean     shared;

  private String      owner;

  private Set<FavoriteDevice> favoriteDevices = new HashSet<FavoriteDevice>(0);

  // Constructors

  /** default constructor */
  public AbstractFavorite() {
  }

  /** minimal constructor */
  public AbstractFavorite(Long favoriteId, String name, boolean shared) {
    this.favoriteId = favoriteId;
    this.name = name;
    this.shared = shared;
  }

  /** full constructor */
  public AbstractFavorite(Long favoriteId, String name, String description, boolean shared, String owner,
      Set<FavoriteDevice> favoriteDevices) {
    this.favoriteId = favoriteId;
    this.name = name;
    this.description = description;
    this.shared = shared;
    this.owner = owner;
    this.favoriteDevices = favoriteDevices;
  }

  // Property accessors

  /*
   * (non-Javadoc)
   * 
   * @see com.hcp.dm.test.hibernate.entity.Favorite#getFavoriteId()
   */
  public Long getFavoriteId() {
    return this.favoriteId;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.hcp.dm.test.hibernate.entity.Favorite#setFavoriteId(java.lang.Long)
   */
  public void setFavoriteId(Long favoriteId) {
    this.favoriteId = favoriteId;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.hcp.dm.test.hibernate.entity.Favorite#getName()
   */
  public String getName() {
    return this.name;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.hcp.dm.test.hibernate.entity.Favorite#setName(java.lang.String)
   */
  public void setName(String name) {
    this.name = name;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.hcp.dm.test.hibernate.entity.Favorite#getDescription()
   */
  public String getDescription() {
    return this.description;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.hcp.dm.test.hibernate.entity.Favorite#setDescription(java.lang.String)
   */
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   * @return the shared
   */
  public boolean isShared() {
    return shared;
  }

  /**
   * @param shared
   *            the shared to set
   */
  public void setShared(boolean shared) {
    this.shared = shared;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.hcp.dm.test.hibernate.entity.Favorite#getOwner()
   */
  public String getOwner() {
    return this.owner;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.hcp.dm.test.hibernate.entity.Favorite#setOwner(java.lang.String)
   */
  public void setOwner(String owner) {
    this.owner = owner;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.hcp.dm.test.hibernate.entity.Favorite#getFavoriteDevices()
   */
  public Set<FavoriteDevice> getFavoriteDevices() {
    return this.favoriteDevices;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.hcp.dm.test.hibernate.entity.Favorite#setFavoriteDevices(java.util.Set)
   */
  public void setFavoriteDevices(Set<FavoriteDevice> favoriteDevices) {
    this.favoriteDevices = favoriteDevices;
  }

}