package com.npower.dm.hibernate.entity;

import com.npower.dm.core.AutomaticProvisionJob;

/**
 * AbstractAutoJobProfileConfigId generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractAutoJobProfileConfigId implements java.io.Serializable {

  // Fields

  private AutomaticProvisionJob autoProvisionJob;

  private long             profileIndex;

  // Constructors

  /** default constructor */
  public AbstractAutoJobProfileConfigId() {
  }

  /** full constructor */
  public AbstractAutoJobProfileConfigId(AutomaticProvisionJob autoProvisionJob, long profileIndex) {
    this.autoProvisionJob = autoProvisionJob;
    this.profileIndex = profileIndex;
  }

  // Property accessors

  public long getProfileIndex() {
    return this.profileIndex;
  }

  public void setProfileIndex(long profileIndex) {
    this.profileIndex = profileIndex;
  }

  /**
   * @return the autoProvisionJob
   */
  public AutomaticProvisionJob getAutoProvisionJob() {
    return autoProvisionJob;
  }

  /**
   * @param autoProvisionJob
   *          the autoProvisionJob to set
   */
  public void setAutoProvisionJob(AutomaticProvisionJob autoProvisionJob) {
    this.autoProvisionJob = autoProvisionJob;
  }

  public boolean equals(Object other) {
    if ((this == other))
      return true;
    if ((other == null))
      return false;
    if (!(other instanceof AbstractAutoJobProfileConfigId))
      return false;
    AbstractAutoJobProfileConfigId castOther = (AbstractAutoJobProfileConfigId) other;

    return ((this.getAutoProvisionJob() == castOther.getAutoProvisionJob()) || (this.getAutoProvisionJob() != null
        && castOther.getAutoProvisionJob() != null && this.getAutoProvisionJob()
        .equals(castOther.getAutoProvisionJob())))
        && ((this.getProfileIndex() == castOther.getProfileIndex()) || (this.getProfileIndex() != 0
            && castOther.getProfileIndex() != 0 && this.getProfileIndex() == castOther.getProfileIndex()));
  }

  public int hashCode() {
    int result = 17;

    result = 37 * result + (getAutoProvisionJob() == null ? 0 : this.getAutoProvisionJob().hashCode());
    result = 37 * result + (getProfileIndex() == 0 ? 0 : (int)this.getProfileIndex());
    return result;
  }

}