/**
 * $Header: /home/master/nWave-DM-Common/src/com/npower/dm/hibernate/entity/AbstractSoftwareVendor.java,v 1.4 2008/09/18 05:50:46 zhao Exp $
 * $Revision: 1.4 $
 * $Date: 2008/09/18 05:50:46 $
 *
 * ===============================================================================================
 * License, Version 1.1
 *
 * Copyright (c) 1994-2006 NPower Network Software Ltd.  All rights reserved.
 *
 * This SOURCE CODE FILE, which has been provided by NPower as part
 * of a NPower product for use ONLY by licensed users of the product,
 * includes CONFIDENTIAL and PROPRIETARY information of NPower.
 *
 * USE OF THIS SOFTWARE IS GOVERNED BY THE TERMS AND CONDITIONS
 * OF THE LICENSE STATEMENT AND LIMITED WARRANTY FURNISHED WITH
 * THE PRODUCT.
 *
 * IN PARTICULAR, YOU WILL INDEMNIFY AND HOLD NPower, ITS RELATED
 * COMPANIES AND ITS SUPPLIERS, HARMLESS FROM AND AGAINST ANY CLAIMS
 * OR LIABILITIES ARISING OUT OF THE USE, REPRODUCTION, OR DISTRIBUTION
 * OF YOUR PROGRAMS, INCLUDING ANY CLAIMS OR LIABILITIES ARISING OUT OF
 * OR RESULTING FROM THE USE, MODIFICATION, OR DISTRIBUTION OF PROGRAMS
 * OR FILES CREATED FROM, BASED ON, AND/OR DERIVED FROM THIS SOURCE
 * CODE FILE.
 * ===============================================================================================
 */
package com.npower.dm.hibernate.entity;

import java.util.HashSet;
import java.util.Set;

import com.npower.dm.core.Software;
import com.npower.dm.core.SoftwareVendor;

/**
 * AbstractSoftwareVendor generated by MyEclipse Persistence Tools
 * 
 * @author Zhao DongLu
 * @version $Revision: 1.4 $ $Date: 2008/09/18 05:50:46 $
 */

public abstract class AbstractSoftwareVendor implements java.io.Serializable, SoftwareVendor, Comparable<SoftwareVendor> {

  // Fields

  private long   id;

  private String name;

  private String   description;

  private String webSite;

  private Set    softwares = new HashSet(0);

  // Constructors

  /** default constructor */
  public AbstractSoftwareVendor() {
  }

  /** minimal constructor */
  public AbstractSoftwareVendor(long vendorId, String name) {
    this.id = vendorId;
    this.name = name;
  }

  /** full constructor */
  public AbstractSoftwareVendor(long vendorId, String name, String description, String webSite, Set<SoftwareEntity> softwares) {
    this.id = vendorId;
    this.name = name;
    this.description = description;
    this.webSite = webSite;
    this.softwares = softwares;
  }

  // Property accessors

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.AAA#getId()
   */
  public long getId() {
    return this.id;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.AAA#setId(long)
   */
  public void setId(long vendorId) {
    this.id = vendorId;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.AAA#getName()
   */
  public String getName() {
    return this.name;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.AAA#setName(java.lang.String)
   */
  public void setName(String name) {
    this.name = name;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.AAA#getDescription()
   */
  public String getDescription() {
    return this.description;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.AAA#setDescription(java.sql.Clob)
   */
  public void setDescription(String description) {
    this.description = description;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.AAA#getWebSite()
   */
  public String getWebSite() {
    return this.webSite;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.AAA#setWebSite(java.lang.String)
   */
  public void setWebSite(String webSite) {
    this.webSite = webSite;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.AAA#getSoftwares()
   */
  public Set<Software> getSoftwares() {
    return this.softwares;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.AAA#setSoftwares(java.util.Set)
   */
  public void setSoftwares(Set<Software> softwares) {
    this.softwares = softwares;
  }

}