/**
 * $Header: /home/master/nWave-DM-Common/src/com/npower/dm/hibernate/entity/AbstractSoftwarePackage.java,v 1.10 2008/09/18 05:50:46 zhao Exp $
 * $Revision: 1.10 $
 * $Date: 2008/09/18 05:50:46 $
 *
 * ===============================================================================================
 * License, Version 1.1
 *
 * Copyright (c) 1994-2006 NPower Network Software Ltd.  All rights reserved.
 *
 * This SOURCE CODE FILE, which has been provided by NPower as part
 * of a NPower product for use ONLY by licensed users of the product,
 * includes CONFIDENTIAL and PROPRIETARY information of NPower.
 *
 * USE OF THIS SOFTWARE IS GOVERNED BY THE TERMS AND CONDITIONS
 * OF THE LICENSE STATEMENT AND LIMITED WARRANTY FURNISHED WITH
 * THE PRODUCT.
 *
 * IN PARTICULAR, YOU WILL INDEMNIFY AND HOLD NPower, ITS RELATED
 * COMPANIES AND ITS SUPPLIERS, HARMLESS FROM AND AGAINST ANY CLAIMS
 * OR LIABILITIES ARISING OUT OF THE USE, REPRODUCTION, OR DISTRIBUTION
 * OF YOUR PROGRAMS, INCLUDING ANY CLAIMS OR LIABILITIES ARISING OUT OF
 * OR RESULTING FROM THE USE, MODIFICATION, OR DISTRIBUTION OF PROGRAMS
 * OR FILES CREATED FROM, BASED ON, AND/OR DERIVED FROM THIS SOURCE
 * CODE FILE.
 * ===============================================================================================
 */
package com.npower.dm.hibernate.entity;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.npower.dm.core.Software;
import com.npower.dm.core.SoftwarePackage;

/**
 * AbstractSoftwarePackage generated by MyEclipse Persistence Tools
 * 
 * @author Zhao DongLu
 * @version $Revision: 1.10 $ $Date: 2008/09/18 05:50:46 $
 */

public abstract class AbstractSoftwarePackage implements java.io.Serializable, SoftwarePackage {

  // Fields

  private long           id;

  private DMBinary       binary;

  private Software software;

  private String         language;

  private String         mimeType;

  private String         url;

  private String         blobFilename;
  
  private String         installationOptions;

  private String         status = Software.STATUS_RELEASE;
  
  private String name = null;
  
  private String description = null;
  
  private Date createdTime = new Date();
  private Date lastUpdatedTime = new Date();
  private String createdBy = null;
  private String lastUpdatedBy = null;
  private long changeVersion = 0;

  private Date           publishedTime = new Date();

  private Set<?>         packageModels = new HashSet<Object>(0);

  private Set<? extends VSoftwareTrackLogAll>            ratings = new HashSet<VSoftwareTrackLogAll>(0);
  private Set<? extends VSoftwareTrackLogDaily>            ratingsDaily = new HashSet<VSoftwareTrackLogDaily>(0);
  private Set<? extends VSoftwareTrackLogWeekly>            ratingsWeekly = new HashSet<VSoftwareTrackLogWeekly>(0);
  private Set<? extends VSoftwareTrackLogMonthly>            ratingsMonthly = new HashSet<VSoftwareTrackLogMonthly>(0);
  private Set<? extends VSoftwareTrackLogYearly>            ratingsYearly = new HashSet<VSoftwareTrackLogYearly>(0);

  // Constructors

  /** default constructor */
  public AbstractSoftwarePackage() {
  }

  /** minimal constructor */
  public AbstractSoftwarePackage(long packageId, String blobFilename) {
    this.id = packageId;
    this.blobFilename = blobFilename;
  }

  // Property accessors

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.AAA#getId()
   */
  public long getId() {
    return this.id;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.AAA#setId(long)
   */
  public void setId(long packageId) {
    this.id = packageId;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.AAA#getBinary()
   */
  public DMBinary getBinary() {
    return this.binary;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.AAA#setBinary(com.npower.dm.core.DMBinary)
   */
  public void setBinary(DMBinary binary) {
    this.binary = binary;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.AAA#getSoftware()
   */
  public Software getSoftware() {
    return this.software;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.AAA#setSoftware(com.npower.dm.core.Software)
   */
  public void setSoftware(Software software) {
    this.software = software;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.AAA#getLanguage()
   */
  public String getLanguage() {
    return this.language;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.AAA#setLanguage(java.lang.String)
   */
  public void setLanguage(String language) {
    this.language = language;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.AAA#getMimeType()
   */
  public String getMimeType() {
    return this.mimeType;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.AAA#setMimeType(java.lang.String)
   */
  public void setMimeType(String mimeType) {
    this.mimeType = mimeType;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.AAA#getUrl()
   */
  public String getUrl() {
    return this.url;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.AAA#setUrl(java.lang.String)
   */
  public void setUrl(String url) {
    this.url = url;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.AAA#getBlobFilename()
   */
  public String getBlobFilename() {
    return this.blobFilename;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.AAA#setBlobFilename(java.lang.String)
   */
  public void setBlobFilename(String blobFilename) {
    this.blobFilename = blobFilename;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.AAA#getPublichedTime()
   */
  public Date getPublishedTime() {
    return this.publishedTime;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.AAA#setPublichedTime(java.util.Date)
   */
  public void setPublishedTime(Date publishedTime) {
    this.publishedTime = publishedTime;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.AAA#getRatings()
   */
  public Set<? extends VSoftwareTrackLogAll> getRatings() {
    return this.ratings;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.AAA#setRatings(java.util.Set)
   */
  public void setRatings(Set<? extends VSoftwareTrackLogAll> ratings) {
    this.ratings = ratings;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.core.SoftwarePackage#getInstallationOptions()
   */
  public String getInstallationOptions() {
    return installationOptions;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.core.SoftwarePackage#setInstallationOptions(java.lang.String)
   */
  public void setInstallationOptions(String installationOptions) {
    this.installationOptions = installationOptions;
  }

  /**
   * @return Returns the packageModels.
   */
  public Set getPackageModels() {
    return packageModels;
  }

  /**
   * @param packageModels The packageModels to set.
   */
  public void setPackageModels(Set packageModels) {
    this.packageModels = packageModels;
  }

  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }

  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public Date getCreatedTime() {
    return createdTime;
  }

  public void setCreatedTime(Date createdTime) {
    this.createdTime = createdTime;
  }

  public Date getLastUpdatedTime() {
    return lastUpdatedTime;
  }

  public void setLastUpdatedTime(Date lastUpdatedTime) {
    this.lastUpdatedTime = lastUpdatedTime;
  }

  public String getCreatedBy() {
    return createdBy;
  }

  public void setCreatedBy(String createdBy) {
    this.createdBy = createdBy;
  }

  public String getLastUpdatedBy() {
    return lastUpdatedBy;
  }

  public void setLastUpdatedBy(String lastUpdatedBy) {
    this.lastUpdatedBy = lastUpdatedBy;
  }

  public long getChangeVersion() {
    return changeVersion;
  }

  public void setChangeVersion(long changeVersion) {
    this.changeVersion = changeVersion;
  }

  /**
   * @return the ratingsDaily
   */
  public Set<? extends VSoftwareTrackLogDaily> getRatingsDaily() {
    return ratingsDaily;
  }

  /**
   * @param ratingsDaily the ratingsDaily to set
   */
  public void setRatingsDaily(Set<? extends VSoftwareTrackLogDaily> ratingsDaily) {
    this.ratingsDaily = ratingsDaily;
  }

  /**
   * @return the ratingsWeekly
   */
  public Set<? extends VSoftwareTrackLogWeekly> getRatingsWeekly() {
    return ratingsWeekly;
  }

  /**
   * @param ratingsWeekly the ratingsWeekly to set
   */
  public void setRatingsWeekly(Set<? extends VSoftwareTrackLogWeekly> ratingsWeekly) {
    this.ratingsWeekly = ratingsWeekly;
  }

  /**
   * @return the ratingsMonthly
   */
  public Set<? extends VSoftwareTrackLogMonthly> getRatingsMonthly() {
    return ratingsMonthly;
  }

  /**
   * @param ratingsMonthly the ratingsMonthly to set
   */
  public void setRatingsMonthly(Set<? extends VSoftwareTrackLogMonthly> ratingsMonthly) {
    this.ratingsMonthly = ratingsMonthly;
  }

  /**
   * @return the ratingsYearly
   */
  public Set<? extends VSoftwareTrackLogYearly> getRatingsYearly() {
    return ratingsYearly;
  }

  /**
   * @param ratingsYearly the ratingsYearly to set
   */
  public void setRatingsYearly(Set<? extends VSoftwareTrackLogYearly> ratingsYearly) {
    this.ratingsYearly = ratingsYearly;
  }

  /**
   * @return the name
   */
  public String getName() {
    return name;
  }

  /**
   * @param name the name to set
   */
  public void setName(String name) {
    this.name = name;
  }

}