/**
 * $Header: /home/master/nWave-DM-Common/src/com/npower/dm/hibernate/entity/AbstractSoftwareRating.java,v 1.2 2008/01/28 10:30:12 zhao Exp $
 * $Revision: 1.2 $
 * $Date: 2008/01/28 10:30:12 $
 *
 * ===============================================================================================
 * License, Version 1.1
 *
 * Copyright (c) 1994-2006 NPower Network Software Ltd.  All rights reserved.
 *
 * This SOURCE CODE FILE, which has been provided by NPower as part
 * of a NPower product for use ONLY by licensed users of the product,
 * includes CONFIDENTIAL and PROPRIETARY information of NPower.
 *
 * USE OF THIS SOFTWARE IS GOVERNED BY THE TERMS AND CONDITIONS
 * OF THE LICENSE STATEMENT AND LIMITED WARRANTY FURNISHED WITH
 * THE PRODUCT.
 *
 * IN PARTICULAR, YOU WILL INDEMNIFY AND HOLD NPower, ITS RELATED
 * COMPANIES AND ITS SUPPLIERS, HARMLESS FROM AND AGAINST ANY CLAIMS
 * OR LIABILITIES ARISING OUT OF THE USE, REPRODUCTION, OR DISTRIBUTION
 * OF YOUR PROGRAMS, INCLUDING ANY CLAIMS OR LIABILITIES ARISING OUT OF
 * OR RESULTING FROM THE USE, MODIFICATION, OR DISTRIBUTION OF PROGRAMS
 * OR FILES CREATED FROM, BASED ON, AND/OR DERIVED FROM THIS SOURCE
 * CODE FILE.
 * ===============================================================================================
 */
package com.npower.dm.hibernate.entity;

import com.npower.dm.core.SoftwarePackage;
import com.npower.dm.core.SoftwareRating;

/**
 * AbstractSoftwareRating generated by MyEclipse Persistence Tools
 * 
 * @author Zhao DongLu
 * @version $Revision: 1.2 $ $Date: 2008/01/28 10:30:12 $
 */

public abstract class AbstractSoftwareRating implements java.io.Serializable, SoftwareRating {

  // Fields

  private long                  id;

  private SoftwarePackage softwarePackage;
  
  private String name;

  private long                  rate = 0;

  // Constructors

  /** default constructor */
  public AbstractSoftwareRating() {
  }

  /** minimal constructor */
  public AbstractSoftwareRating(long ratingId) {
    this.id = ratingId;
  }

  /** full constructor */
  public AbstractSoftwareRating(long ratingId, String name, SoftwarePackage softwarePackage, long rate) {
    this.id = ratingId;
    this.name = name;
    this.softwarePackage = softwarePackage;
    this.rate = rate;
  }

  // Property accessors

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.AAA#getId()
   */
  public long getId() {
    return this.id;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.AAA#setId(long)
   */
  public void setId(long ratingId) {
    this.id = ratingId;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.core.SoftwareRating#getName()
   */
  public String getName() {
    return this.name;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.core.SoftwareRating#setName(java.lang.String)
   */
  public void setName(String name) {
    this.name = name;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.AAA#getSoftwarePackage()
   */
  public SoftwarePackage getSoftwarePackage() {
    return this.softwarePackage;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.AAA#setSoftwarePackage(com.npower.dm.core.SoftwarePackage)
   */
  public void setSoftwarePackage(SoftwarePackage softwarePackage) {
    this.softwarePackage = softwarePackage;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.AAA#getRate()
   */
  public long getRate() {
    return this.rate;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.AAA#setRate(long)
   */
  public void setRate(long rate) {
    this.rate = rate;
  }

}