/**
 * $Header: /home/master/nWave-DM-Common/src/com/npower/dm/hibernate/entity/AbstractSoftwareCategory.java,v 1.4 2008/09/18 05:50:46 zhao Exp $
 * $Revision: 1.4 $
 * $Date: 2008/09/18 05:50:46 $
 *
 * ===============================================================================================
 * License, Version 1.1
 *
 * Copyright (c) 1994-2006 NPower Network Software Ltd.  All rights reserved.
 *
 * This SOURCE CODE FILE, which has been provided by NPower as part
 * of a NPower product for use ONLY by licensed users of the product,
 * includes CONFIDENTIAL and PROPRIETARY information of NPower.
 *
 * USE OF THIS SOFTWARE IS GOVERNED BY THE TERMS AND CONDITIONS
 * OF THE LICENSE STATEMENT AND LIMITED WARRANTY FURNISHED WITH
 * THE PRODUCT.
 *
 * IN PARTICULAR, YOU WILL INDEMNIFY AND HOLD NPower, ITS RELATED
 * COMPANIES AND ITS SUPPLIERS, HARMLESS FROM AND AGAINST ANY CLAIMS
 * OR LIABILITIES ARISING OUT OF THE USE, REPRODUCTION, OR DISTRIBUTION
 * OF YOUR PROGRAMS, INCLUDING ANY CLAIMS OR LIABILITIES ARISING OUT OF
 * OR RESULTING FROM THE USE, MODIFICATION, OR DISTRIBUTION OF PROGRAMS
 * OR FILES CREATED FROM, BASED ON, AND/OR DERIVED FROM THIS SOURCE
 * CODE FILE.
 * ===============================================================================================
 */
package com.npower.dm.hibernate.entity;

import java.util.HashSet;
import java.util.Set;
import java.util.TreeSet;

import com.npower.dm.core.SoftwareCategory;

/**
 * AbstractSoftwareCategory generated by MyEclipse Persistence Tools
 * 
 * @author Zhao DongLu
 * @version $Revision: 1.4 $ $Date: 2008/09/18 05:50:46 $
 */

public abstract class AbstractSoftwareCategory implements java.io.Serializable, Comparable<SoftwareCategory>, SoftwareCategory {

  // Fields

  private long                   id;

  private SoftwareCategory parent;

  private String                 name;

  private String                   description;

  private Set                    children = new TreeSet();

  private Set<SoftwareCategoriesEntity>                    softwareCategoriesSet = new HashSet<SoftwareCategoriesEntity>(0);
  private Set<SoftwareRecommendEntity>                    recommends = new HashSet<SoftwareRecommendEntity>(0);
  // Constructors

  public Set<SoftwareCategoriesEntity> getSoftwareCategoriesSet() {
    return softwareCategoriesSet;
  }

  public void setSoftwareCategoriesSet(Set<SoftwareCategoriesEntity> softwareCategoriesSet) {
    this.softwareCategoriesSet = softwareCategoriesSet;
  }

  public Set<SoftwareRecommendEntity> getRecommends() {
    return recommends;
  }

  public void setRecommends(Set<SoftwareRecommendEntity> recommends) {
    this.recommends = recommends;
  }

  /** default constructor */
  public AbstractSoftwareCategory() {
  }

  /** minimal constructor */
  public AbstractSoftwareCategory(long categoryId, String name) {
    this.id = categoryId;
    this.name = name;
  }

  // Property accessors

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.AA#getId()
   */
  public long getId() {
    return this.id;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.AA#setId(long)
   */
  public void setId(long categoryId) {
    this.id = categoryId;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.AA#getParent()
   */
  public SoftwareCategory getParent() {
    return this.parent;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.AA#setParent(com.npower.dm.core.SoftwareCategory)
   */
  public void setParent(SoftwareCategory category) {
    this.parent = category;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.AA#getName()
   */
  public String getName() {
    return this.name;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.AA#setName(java.lang.String)
   */
  public void setName(String name) {
    this.name = name;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.AA#getDescription()
   */
  public String getDescription() {
    return this.description;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.AA#setDescription(java.sql.Clob)
   */
  public void setDescription(String description) {
    this.description = description;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.AA#getChildren()
   */
  public Set<SoftwareCategory> getChildren() {
    return this.children;
  }

  /* (non-Javadoc)
   * @see com.npower.dm.hibernate.entity.AA#setChildren(java.util.Set)
   */
  public void setChildren(Set<SoftwareCategory> children) {
    this.children = children;
  }

}