package com.npower.dm.hibernate.entity;
// default package

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * AbstractAuditLogEntity generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractAuditLogEntity implements java.io.Serializable {

  // Fields

  private long           ID;

  private AuditLogAction action;

  private String         userName;

  private Date           creationDate = new Date();

  private String         description;

  private String         ipAddress;
  
  private Set<AuditLogTargetEntity> targets = new HashSet<AuditLogTargetEntity>();

  // Constructors

  /** default constructor */
  public AbstractAuditLogEntity() {
  }

  /** minimal constructor */
  public AbstractAuditLogEntity(AuditLogAction action, String userName, Date creationDate) {
    this.action = action;
    this.userName = userName;
    this.creationDate = creationDate;
  }

  /** full constructor */
  public AbstractAuditLogEntity(AuditLogAction action, String userName, Date creationDate,
      String description) {
    this.action = action;
    this.userName = userName;
    this.creationDate = creationDate;
    this.description = description;
  }

  // Property accessors

  public long getID() {
    return this.ID;
  }

  public void setID(long ID) {
    this.ID = ID;
  }

  public AuditLogAction getAction() {
    return this.action;
  }

  public void setAction(AuditLogAction action) {
    this.action = action;
  }

  public String getUserName() {
    return this.userName;
  }

  public void setUserName(String userName) {
    this.userName = userName;
  }

  public Date getCreationDate() {
    return this.creationDate;
  }

  public void setCreationDate(Date creationDate) {
    this.creationDate = creationDate;
  }

  public String getDescription() {
    return this.description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  /**
   * @return the ipAddress
   */
  public String getIpAddress() {
    return ipAddress;
  }

  /**
   * @param ipAddress the ipAddress to set
   */
  public void setIpAddress(String ipAddress) {
    this.ipAddress = ipAddress;
  }

  /**
   * @return the targets
   */
  public Set<AuditLogTargetEntity> getTargets() {
    return targets;
  }

  /**
   * @param targets the targets to set
   */
  public void setTargets(Set<AuditLogTargetEntity> targets) {
    this.targets = targets;
  }

}