package com.npower.dm.hibernate.entity;



/**
 * AbstractAutoJobNodesDiscover generated by MyEclipse - Hibernate Tools
 */

public abstract class AbstractAutoJobNodesDiscover  implements java.io.Serializable {


    // Fields    

     private AutoJobNodesDiscoverId id;
     private String nodeName;


    // Constructors

    /** default constructor */
    public AbstractAutoJobNodesDiscover() {
    }

	/** minimal constructor */
    public AbstractAutoJobNodesDiscover(AutoJobNodesDiscoverId id) {
        this.id = id;
    }
    
    /** full constructor */
    public AbstractAutoJobNodesDiscover(AutoJobNodesDiscoverId id, String nodeName) {
        this.id = id;
        this.nodeName = nodeName;
    }

   
    // Property accessors

    public AutoJobNodesDiscoverId getId() {
        return this.id;
    }
    
    public void setId(AutoJobNodesDiscoverId id) {
        this.id = id;
    }

    public String getNodeName() {
        return this.nodeName;
    }
    
    public void setNodeName(String nodeName) {
        this.nodeName = nodeName;
    }
   








}