package com.npower.dm.hibernate.entity;
// default package
// Generated by MyEclipse - Hibernate Tools

/**
 * AuditLogAction generated by MyEclipse - Hibernate Tools
 */
public class AuditLogAction extends AbstractAuditLogAction implements java.io.Serializable {

  // Constructors

  /** default constructor */
  public AuditLogAction() {
  }

  /** minimal constructor */
  public AuditLogAction(String value, String description, String type, boolean optional) {
    super(value, description, type, optional);
  }

}
