package com.npower.dm.hibernate.entity;

// Generated by MyEclipse - Hibernate Tools

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import org.apache.commons.lang.StringUtils;

import com.npower.dm.core.ProfileConfig;

/**
 * AutomaticProvisionJob generated by MyEclipse - Hibernate Tools
 */
public class AutoProvisionJobEntity extends AbstractAutoProvisionJob implements java.io.Serializable {

  // Constructors

  /** default constructor */
  public AutoProvisionJobEntity() {
  }

  /** minimal constructor */
  public AutoProvisionJobEntity(Long provReqId, String type, String jobType, String jobTypeForDisplay, String state,
      boolean running, Date scheduledTime, Long changeVersion) {
    super(provReqId, type, jobType, jobTypeForDisplay, state, running, scheduledTime, changeVersion);
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.npower.dm.core.AutomaticProvisionJob#getDiscoveryNodes()
   */
  public List<String> getDiscoveryNodes() {
    List<String> result = new ArrayList<String>();
    for (AutoJobNodesDiscover node : this.getAutoJobNodesDiscovers()) {
      String nodePath = node.getNodeName();
      if (StringUtils.isNotEmpty(nodePath)) {
        result.add(nodePath);
      }
    }
    return result;
  }

  /*
   * (non-Javadoc)
   * 
   * @see com.npower.dm.core.AutomaticProvisionJob#getProfileConfigs()
   */
  public List<ProfileConfig> getProfileConfigs() {
    List<ProfileConfig> result = new ArrayList<ProfileConfig>();
    for (AutoJobProfileConfig jobState : this.getAutoJobProfileConfigs()) {
      ProfileConfig profile = jobState.getProfileConfig();
      if (profile != null) {
        result.add(profile);
      }
    }
    return result;
  }

}
