package com.npower.dm.hibernate.entity;

import com.npower.dm.core.AutomaticProvisionJob;



/**
 * AutoJobNodesDiscoverId generated by MyEclipse - Hibernate Tools
 */
public class AutoJobNodesDiscoverId extends AbstractAutoJobNodesDiscoverId implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public AutoJobNodesDiscoverId() {
    }

    
    /** full constructor */
    public AutoJobNodesDiscoverId(AutomaticProvisionJob autoProvisionJob, Long nodeIndex) {
        super(autoProvisionJob, nodeIndex);        
    }
   
}
