package com.npower.dm.hibernate.entity;

// Generated by MyEclipse - Hibernate Tools

/**
 * AutoJobNodesDiscover generated by MyEclipse - Hibernate Tools
 */
public class AutoJobNodesDiscover extends AbstractAutoJobNodesDiscover implements java.io.Serializable, Comparable<AutoJobNodesDiscover> {

  // Constructors

  /** default constructor */
  public AutoJobNodesDiscover() {
    super();
  }

  /** minimal constructor */
  public AutoJobNodesDiscover(AutoJobNodesDiscoverId id) {
    super(id);
  }

  /** full constructor */
  public AutoJobNodesDiscover(AutoJobNodesDiscoverId id, String nodeName) {
    super(id, nodeName);
  }

  /* (non-Javadoc)
   * @see java.lang.Comparable#compareTo(java.lang.Object)
   */
  public int compareTo(AutoJobNodesDiscover other) {
    if (other == null) {
       return 1;
    }
    return (int)(this.getId().getNodeIndex()- other.getId().getNodeIndex());
  }

}
