package com.npower.dm.hibernate.entity;
// default package
// Generated by MyEclipse Persistence Tools

import java.util.Date;


/**
 * ClientProvAuditLogEntity generated by MyEclipse Persistence Tools
 */
public class ClientProvAuditLogEntity extends AbstractClientProvAuditLogEntity implements java.io.Serializable {

    // Constructors

    /** default constructor */
    public ClientProvAuditLogEntity() {
    }

	/** minimal constructor */
    public ClientProvAuditLogEntity(Date timeStamp, String devicePhoneNumber, String status) {
        super(timeStamp, devicePhoneNumber, status);        
    }
    
    /** full constructor */
    public ClientProvAuditLogEntity(Date timeStamp, String devicePhoneNumber, String manufacturerExtID, String modelExtID, String carrierExtID, String status, String profileCategoryName, String profileName, String profileContent, String memo) {
        super( timeStamp, devicePhoneNumber, manufacturerExtID, modelExtID, carrierExtID, status, profileCategoryName, profileName, profileContent, memo);        
    }
   
}
