package com.npower.dm.hibernate.entity;

import java.util.Date;

/**
 * DmDeviceChangeLog generated by MyEclipse Persistence Tools
 */

public class DmDeviceChangeLog implements java.io.Serializable {

  // Fields

  private long   id;

  private String imei;

  private String phoneNumber;

  private String imsi;

  private String brand;

  private String model;
  
  private String softwareVersion;

  private Date   lastUpdate;

  // Constructors

  /** default constructor */
  public DmDeviceChangeLog() {
  }

  /** minimal constructor */
  public DmDeviceChangeLog(String imei, String phoneNumber, Date lastUpdate) {
    this.imei = imei;
    this.phoneNumber = phoneNumber;
    this.lastUpdate = lastUpdate;
  }

  /** full constructor */
  public DmDeviceChangeLog(String imei, String phoneNumber, String imsi, String brand, String model, Date lastUpdate) {
    this.imei = imei;
    this.phoneNumber = phoneNumber;
    this.imsi = imsi;
    this.brand = brand;
    this.model = model;
    this.lastUpdate = lastUpdate;
  }

  // Property accessors

  public long getId() {
    return this.id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public String getImei() {
    return this.imei;
  }

  public void setImei(String imei) {
    this.imei = imei;
  }

  public String getPhoneNumber() {
    return this.phoneNumber;
  }

  public void setPhoneNumber(String phoneNumber) {
    this.phoneNumber = phoneNumber;
  }

  public String getImsi() {
    return this.imsi;
  }

  public void setImsi(String imsi) {
    this.imsi = imsi;
  }

  public String getBrand() {
    return this.brand;
  }

  public void setBrand(String brand) {
    this.brand = brand;
  }

  public String getModel() {
    return this.model;
  }

  public void setModel(String model) {
    this.model = model;
  }

  public Date getLastUpdate() {
    return this.lastUpdate;
  }

  public void setLastUpdate(Date lastUpdate) {
    this.lastUpdate = lastUpdate;
  }

  /**
   * @return the softwareVersion
   */
  public String getSoftwareVersion() {
    return softwareVersion;
  }

  /**
   * @param softwareVersion the softwareVersion to set
   */
  public void setSoftwareVersion(String softwareVersion) {
    this.softwareVersion = softwareVersion;
  }

}