package com.npower.dm.hibernate.entity;

import java.util.Date;


/**
 * DmTrackingLogHttp generated by MyEclipse Persistence Tools
 */

public class  DmTrackingLogHttp implements java.io.Serializable {


    // Fields

     private long id;
     private Date timeStamp;
     private String dmSessionId;
     private long dmRequestSize;
     private long dmResponseSize;
     private String clientIp;
     private String userAgent;


    // Constructors

    /** default constructor */
    public DmTrackingLogHttp() {
    }

	/** minimal constructor */
    public DmTrackingLogHttp(Date timeStamp, long dmRequestSize, long dmResponseSize, String clientIp) {
        this.timeStamp = timeStamp;
        this.dmRequestSize = dmRequestSize;
        this.dmResponseSize = dmResponseSize;
        this.clientIp = clientIp;
    }
    
    /** full constructor */
    public DmTrackingLogHttp(Date timeStamp,String dmSessionId, long dmRequestSize, long dmResponseSize, String clientIp, String userAgent) {
        this.dmSessionId = dmSessionId;
        this.dmRequestSize = dmRequestSize;
        this.dmResponseSize = dmResponseSize;
        this.clientIp = clientIp;
        this.userAgent = userAgent;
    }

   
    // Property accessors

    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }

    public Date getTimeStamp() {
        return this.timeStamp;
    }
    
    public void setTimeStamp(Date timeStamp) {
        this.timeStamp = timeStamp;
    }

    public String getDmSessionId() {
        return this.dmSessionId;
    }
    
    public void setDmSessionId(String dmSessionId) {
        this.dmSessionId = dmSessionId;
    }

    public long getDmRequestSize() {
        return this.dmRequestSize;
    }
    
    public void setDmRequestSize(long dmRequestSize) {
        this.dmRequestSize = dmRequestSize;
    }

    public long getDmResponseSize() {
        return this.dmResponseSize;
    }
    
    public void setDmResponseSize(long dmResponseSize) {
        this.dmResponseSize = dmResponseSize;
    }

    public String getClientIp() {
        return this.clientIp;
    }
    
    public void setClientIp(String clientIp) {
        this.clientIp = clientIp;
    }

    public String getUserAgent() {
        return this.userAgent;
    }
    
    public void setUserAgent(String userAgent) {
        this.userAgent = userAgent;
    }
   








}