package com.npower.dm.hibernate.entity;

import java.util.Date;

/**
 * DmTrackingLogJob generated by MyEclipse Persistence Tools
 */

public class DmTrackingLogJob implements java.io.Serializable {

  // Fields

  private long   id;

  private String dmSessionId;

  private String deviceExternalId;

  private String processor;

  private String statusCode;

  private long   jobId;

  private Date   beginTimeStamp;

  private Date   endTimeStamp;

  private Date   updatedTime;

  // Constructors

  /** default constructor */
  public DmTrackingLogJob() {
  }

  /** minimal constructor */
  public DmTrackingLogJob(String dmSessionId, String deviceExternalId, String processor, Date updatedTime) {
    this.dmSessionId = dmSessionId;
    this.deviceExternalId = deviceExternalId;
    this.processor = processor;
    this.updatedTime = updatedTime;
  }

  /** full constructor */
  public DmTrackingLogJob(String dmSessionId, String deviceExternalId, String processor, String statusCode, long jobId,
      Date beginTimeStamp, Date endTimeStamp, Date updatedTime) {
    this.dmSessionId = dmSessionId;
    this.deviceExternalId = deviceExternalId;
    this.processor = processor;
    this.statusCode = statusCode;
    this.jobId = jobId;
    this.beginTimeStamp = beginTimeStamp;
    this.endTimeStamp = endTimeStamp;
    this.updatedTime = updatedTime;
  }

  // Property accessors

  public long getId() {
    return this.id;
  }

  public void setId(long id) {
    this.id = id;
  }

  public String getDmSessionId() {
    return this.dmSessionId;
  }

  public void setDmSessionId(String dmSessionId) {
    this.dmSessionId = dmSessionId;
  }

  public String getDeviceExternalId() {
    return this.deviceExternalId;
  }

  public void setDeviceExternalId(String deviceExternalId) {
    this.deviceExternalId = deviceExternalId;
  }

  public String getProcessor() {
    return this.processor;
  }

  public void setProcessor(String processor) {
    this.processor = processor;
  }

  public String getStatusCode() {
    return this.statusCode;
  }

  public void setStatusCode(String statusCode) {
    this.statusCode = statusCode;
  }

  public long getJobId() {
    return this.jobId;
  }

  public void setJobId(long jobId) {
    this.jobId = jobId;
  }

  public Date getBeginTimeStamp() {
    return this.beginTimeStamp;
  }

  public void setBeginTimeStamp(Date beginTimeStamp) {
    this.beginTimeStamp = beginTimeStamp;
  }

  public Date getEndTimeStamp() {
    return this.endTimeStamp;
  }

  public void setEndTimeStamp(Date endTimeStamp) {
    this.endTimeStamp = endTimeStamp;
  }

  public Date getUpdatedTime() {
    return this.updatedTime;
  }

  public void setUpdatedTime(Date updatedTime) {
    this.updatedTime = updatedTime;
  }

}