package com.npower.dm.hibernate.entity;

import com.npower.dm.core.Favorite;


// Generated by MyEclipse Persistence Tools

/**
 * FavoriteDevice generated by MyEclipse Persistence Tools
 */
public class FavoriteDeviceEntity extends AbstractFavoriteDevice implements java.io.Serializable {

  // Constructors

  /**
   * 
   */
  private static final long serialVersionUID = 1L;

  /** default constructor */
  public FavoriteDeviceEntity() {
  }

  /** minimal constructor */
  public FavoriteDeviceEntity(Long id, Favorite favorite) {
    super(id, favorite);
  }

  /** full constructor */
  public FavoriteDeviceEntity(Long id, Favorite favorite, Long deviceId) {
    super(id, favorite, deviceId);
  }

}
