package com.npower.dm.hibernate.entity;

import java.util.Date;

import com.npower.dm.core.Software;
import com.npower.dm.core.SoftwarePackage;

/**
 * SoftwareTrackingLog generated by MyEclipse Persistence Tools
 */

public class SoftwareTrackingLog extends AbstractSoftwareTrackingLog implements java.io.Serializable {

  // Fields

  /** default constructor */
  public SoftwareTrackingLog() {
    super();
  }

  /** minimal constructor */
  public SoftwareTrackingLog(String trackingType, Date timeStamp) {
    super(trackingType, timeStamp);
  }

  /** full constructor */
  public SoftwareTrackingLog(SoftwarePackage nwDmSoftwarePackage, Software nwDmSoftware,
      String trackingType, Date timeStamp, String clientIp, String phoneNumber) {
    super(nwDmSoftwarePackage, nwDmSoftware, trackingType, timeStamp, clientIp, phoneNumber);
  }

}