package com.npower.dm.hibernate.entity;


import java.util.Date;

import com.npower.dm.core.Software;

/**
 * SoftwareEvaluateEntity generated by MyEclipse Persistence Tools
 */

public class SoftwareEvaluateEntity extends AbstractSoftwareEvaluateEntity implements java.io.Serializable {

  // Fields

  /** default constructor */
  public SoftwareEvaluateEntity() {
  }

  /** minimal constructor */
  public SoftwareEvaluateEntity(Software Software, long grade, Date createdTime) {
    super(Software, grade, createdTime);
  }

  /** full constructor */
  public SoftwareEvaluateEntity(Software Software, String remark, long grade, String userName, String userIp,
      Date createdTime) {
    super(Software, remark, grade, userName, userIp, createdTime);
  }

}