package com.npower.dm.hibernate.entity;

import com.npower.dm.core.Software;
import com.npower.dm.core.SoftwarePackage;

/**
 * VSoftwareTrackLogDaily generated by MyEclipse Persistence Tools
 */

public class VSoftwareTrackLogDaily extends AbstractVSoftwareTrackLogDaily implements java.io.Serializable {

  // Fields

  public VSoftwareTrackLogDaily() {
    super();
  }
  
  /** minimal constructor */
  public VSoftwareTrackLogDaily(long id, String trackingType) {
    super(id, trackingType);
  }

  /**
   * @param software
   * @param softwarePackage
   * @param trackingType
   * @param dayOfYear
   */
  public VSoftwareTrackLogDaily(long id, Software software, SoftwarePackage softwarePackage, String trackingType, String dayOfYear,long count) {
    super(id, software, softwarePackage, trackingType, dayOfYear,count);
  }


}