package com.npower.dm.hibernate.entity;

import com.npower.dm.core.Software;
import com.npower.dm.core.SoftwarePackage;

/**
 * VSoftwareTrackLogWeekly generated by MyEclipse Persistence Tools
 */

public class VSoftwareTrackLogWeekly extends AbstractVSoftwareTrackLogWeekly implements java.io.Serializable {

  // Fields

  /** default constructor */
  public VSoftwareTrackLogWeekly() {
    super();
  }

  /** minimal constructor */
  public VSoftwareTrackLogWeekly(long id, String trackingType) {
    super(id, trackingType);
  }

  /** full constructor */
  public VSoftwareTrackLogWeekly(long id, Software software, SoftwarePackage softwarePackage, String trackingType, String weekOfYear,long count) {
    super(id, software, softwarePackage, trackingType, weekOfYear, count);
  }

}