package com.npower.dm.hibernate.entity;

import com.npower.dm.core.Software;
import com.npower.dm.core.SoftwarePackage;

/**
 * VSoftwareTrackLogMonthly generated by MyEclipse Persistence Tools
 */

public class VSoftwareTrackLogMonthly extends AbstractVSoftwareTrackLogMonthly implements java.io.Serializable {

  // Fields

  /** default constructor */
  public VSoftwareTrackLogMonthly() {
  }

  /** minimal constructor */
  public VSoftwareTrackLogMonthly(long id ,String trackingType) {
    super(id, trackingType);
  }

  /** full constructor */
  public VSoftwareTrackLogMonthly(long id, Software software, SoftwarePackage softwarePackage, String trackingType, String monthOfYear, long count) {
    super(id, software, softwarePackage, trackingType, monthOfYear, count);
  }

}